In [1]:
import pandas as pd
import scipy as sc
import numpy as np
import os

In [2]:
left = pd.read_csv('./left_target_P200.csv')
right = pd.read_csv('./right_target_P200.csv')

In [3]:
left

,cueValid_silence,cueValid_white,cueValid_lofi,cueInvalid_silence,cueInvalid_white,cueInvalid_lofi
0,7.936778,7.909193,9.591608,4.601610,4.954754,5.514866
1,2.256756,2.500711,3.659562,-5.285469,1.344212,1.163790
2,2.971363,1.490447,3.702669,1.643040,-1.179503,2.763108
3,5.343035,6.738006,6.258940,4.661086,1.157083,8.169650
4,0.743428,-0.610388,1.938449,0.333825,-2.570596,-4.688955
5,8.832520,10.198753,8.450129,10.084850,13.148284,10.513561
6,9.037073,6.010325,7.809071,7.822569,6.588789,8.242138
7,11.933241,13.543688,12.362781,13.034586,16.668791,10.281336
8,6.390129,7.225606,7.446569,2.947672,5.569599,4.390946
9,7.090419,5.552380,8.019185,6.215966,8.019473,5.142886
10,7.049176,5.913133,4.969659,9.178427,2.404815,12.403575

In [4]:
right

,cueValid_silence,cueValid_white,cueValid_lofi,cueInvalid_silence,cueInvalid_white,cueInvalid_lofi
0,9.305009,6.063435,10.752327,5.435749,6.742513,9.471748
1,0.646364,-0.697965,1.295763,-1.050626,-2.636322,-5.190796
2,3.412018,6.209264,4.910483,2.596610,3.580407,6.609209
3,4.275257,5.144619,5.306361,5.691707,0.465989,2.421482
4,-2.399448,0.127587,-3.922633,3.891274,-3.970627,-1.059447
5,8.155348,6.881073,9.254598,3.596795,6.633442,7.005985
6,7.241549,4.848736,4.183619,7.819613,8.936692,5.587849
7,4.836548,6.150224,8.498647,6.013620,6.974308,7.163940
8,4.656599,5.926923,6.468646,4.697678,5.266080,3.239571
9,8.746956,5.602080,8.514081,2.109845,8.341399,6.000659
10,1.850998,7.632670,3.583479,0.964761,3.754181,4.698821

In [7]:
both = right.combine(left, lambda a,b: (a+b)/2)

In [8]:
both

,cueValid_silence,cueValid_white,cueValid_lofi,cueInvalid_silence,cueInvalid_white,cueInvalid_lofi
0,8.620893,6.986314,10.171968,5.018680,5.848633,7.493307
1,1.451560,0.901373,2.477663,-3.168048,-0.646055,-2.013503
2,3.191691,3.849855,4.306576,2.119825,1.200452,4.686159
3,4.809146,5.941313,5.782651,5.176397,0.811536,5.295566
4,-0.828010,-0.241400,-0.992092,2.112549,-3.270612,-2.874201
5,8.493934,8.539913,8.852363,6.840822,9.890863,8.759773
6,8.139311,5.429530,5.996345,7.821091,7.762740,6.914993
7,8.384895,9.846956,10.430714,9.524103,11.821549,8.722638
8,5.523364,6.576264,6.957608,3.822675,5.417840,3.815259
9,7.918687,5.577230,8.266633,4.162905,8.180436,5.571773
10,4.450087,6.772902,4.276569,5.071594,3.079498,8.551198

In [25]:
both.to_csv('./p200.csv',
           index= False,
           encoding= 'utf8')

In [27]:
(right.iloc[10, 5] + left.iloc[10, 5])/2

8.55119805

In [28]:
both.describe()

,cueValid_silence,cueValid_white,cueValid_lofi,cueInvalid_silence,cueInvalid_white,cueInvalid_lofi
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,5.468687,5.470932,6.047909,4.409327,4.554262,4.992996
std,3.212063,3.002587,3.440687,3.368235,4.720808,4.044711
min,-0.828010,-0.241400,-0.992092,-3.168048,-3.270612,-2.874201
25%,3.820889,4.639693,4.291572,2.971250,1.005994,4.250709
50%,5.523364,5.941313,5.996345,5.018680,5.417840,5.571773
75%,8.262103,6.879608,8.559498,6.008610,7.971588,8.022253
max,8.620893,9.846956,10.430714,9.524103,11.821549,8.759773

1.5